### ISSUE TITLE
(支出)drop downでカテゴリ一覧を表示

### ISSUE THREAD

**Issue by Ryoma137** [Ryoma137/record-of-expense#2]
- [x] カテゴリー一覧をDBから取得
- [x] カテゴリー一覧をDBから取得テスト作成
- [x] htmlで画面作成
- [x] 作成した画面にDBから取得したカテゴリーを表示
- [x] 作成した画面にDBから取得したカテゴリーを表示テスト作成

**Comment by Ryoma137** [comment]
- カテゴリー一覧をDBから取得
　　　-  repositoryで取得するデータ(category)を絞ってデータをDBから取得。

下記を参考に @queryをつけてqueryを生成する。
https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.query-methods.at-query

**Comment by Ryoma137** [comment]
- カテゴリー一覧をDBから取得テスト作成
    - testを書いて実行をすると、` Unique index or primary key violation:`が発生、primary keyが重複しているのでテストを実行毎にsqlのデータが削除されていないことを確認。→ test-schema.sqlに`TRUNCATE `文を追加し、実行のたびにデータを削除するようにsqlを変更。

**Comment by Ryoma137** [comment]
- htmlで画面作成
     expense.htmlを作成後、controllerで `return"expense";`とexpenseを返し、 @GetMappingで指定したURIに接続してもhtmlファイルが読み込まれず、`expense`という文字のみ表示される。

**Comment by Ryoma137** [comment]
HTMLで返すためにIncomeControllerのアノテーションを@RestControllerではなく、@Controllerに変更。
すると、'Cannot invoke "com.recordofexpense.recordofexpense.service.AmountService.getCategoryList()" because "this.amountService" is null'のエラーが発生。
実行時にDBにデータがinsertされるSQLファイルが必要なのかと思いsrc/main/resources下にsqlファイルを作成し、`INSERT`文を記載。
その後実行すると、エラーログ`Table "AMOUNT" not found (this database is empty)`が表示される。（H2は組み込みのDBで実行時にDBが作成されるが、DBが作成する前にINSERTをしようとして table not found になっていると推測している）

**Comment by t-ita** [comment]
@Ryoma137 また迷走しそうな感じです。ログをしっかりと読んで理解しましょう。
> すると、Cannot invoke "com.recordofexpense.recordofexpense.service.AmountService.getCategoryList()" because "this.amountService" is nullのエラーが発生。
これは、単に（どこかの）amountService が null だよって要ってるだけなので、DB は関係ないです。
エラーログに表示されるスタックトレースを見ると、どこでエラーが発生しているのかわかるので、それをもとにエラー箇所を探りましょう

**Comment by Ryoma137** [comment]
@AllArgsConstructorをつけてconstructorを生成。
すると、`Circular view path [expense]: would dispatch back to the current handler URL [/expense] again`のエラーが発生。
	→ `pom.xml`に以下のdependencyを追加。

`<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-thymeleaf</artifactId>
</dependency>`

実行後、今度は `Could not parse as each: "categoryList: ${categoryLists}}" (template: "expense" - line 27, col 23)`のエラーが発生。
Thymeleaf側でデータの表示機能で何かしらのエラー(データの表示の仕方が間違っている)が発生していると推測。

**Comment by Ryoma137** [comment]
testGetCategory をactualのリストに 各カテゴリーの文字列が入っているテストに変更 done *push済

**Comment by Ryoma137** [comment]
テストに記述された（getCategoryList の）仕様に合わせて、getCategoryListの実装を変更 done *push済

**Comment by Ryoma137** [comment]
作成した画面にDBから取得したカテゴリーを表示(thymeleafの修正)　着手開始

**Comment by Ryoma137** [comment]
DBから取得したデータをthymeleafで表示させるために以下のコードを追加。drop downリストは表示されるが、リスト内に値が何も入ってない。

`<select name="category">
            <option th:each="categoryList : ${categoryLists}"
               th:text = "${categoryList.category}">
            </option>`

**Comment by Ryoma137** [comment]
テストケース一覧
 * FindAllでDBに保存されている情報が全て取得できているかのテスト
 	* 取得した情報がnullではない
 	* 予測したDBのレコード数が取得される
 	* 予測した各フィールド情報(ID,name,price,category,comments)が取得される

* testGetCategoryでDBに保存されているcategory情報をcategory名の重複がなく取得しているかのテスト。
 	* 予測したDBのレコード数が取得される
 	* 取得した配列の文字列が予測した値と同じである

**Comment by Ryoma137** [comment]
マージ済
